name: Deploy to Railway

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Run tests
        run: mvn test

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          service: "deploy-api-by-github-action"  # Thay bằng tên dịch vụ trên Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}