name: Deploy to Railway

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up environment variables
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_SECRET=${{ secrets.AWS_ACCESS_KEY_SECRET }}" >> $GITHUB_ENV
          echo "OPENAI_ASSISTANT_ID=${{ secrets.OPENAI_ASSISTANT_ID }}" >> $GITHUB_ENV
          echo "SERVER_URI=${{ secrets.SERVER_URI }}" >> $GITHUB_ENV
          echo "SPRING_AI_OPENAI_API_KEY=${{ secrets.SPRING_AI_OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "SPRING_DATA_MONGODB_URI=${{ secrets.SPRING_DATA_MONGODB_URI }}" >> $GITHUB_ENV
          echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "STRIPE_API_SECRET_KEY=${{ secrets.STRIPE_API_SECRET_KEY }}" >> $GITHUB_ENV
          echo "STRIPE_WEBHOOK_SIGNING_SECRET=${{ secrets.STRIPE_WEBHOOK_SIGNING_SECRET }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Run tests
        run: mvn test

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          service: "deploy-api-by-github-action"  # Thay bằng tên dịch vụ trên Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}